### PR TITLE
changed height of bottom bar to depend on height if very tall screen

### PR DESCRIPTION
**Pull request by CharlesYu2000**
maybe

### CODE REVIEW

**Comment by CharlesYu2000** [comment]
Ya so it is true that I made the padding bigger to account for the iPhone line thingy, but I believe the case is that this would look unnatural on other phones that have a bar that is not overlaid on the screen but occupies part of the screen that is completely separate from the app. For now it is probably fine like this, but might be worth investigating how other apps like WeChat handle this issue across platforms

**Comment by SCAuFish** [comment]
Fixed the issue I mentioned in the comment. But I noticed that in iOS version we are unable to see the bar underlining the active icon while in the past it exists. Why is that?
WeChat Image_20191120031135

**Comment by yil578** [comment]
your fix to make the dimension dynamic across devices is good! 👍 I made the active bar shown again, but style still needs to be fixed

**Comment by SCAuFish** [comment]
Let me merge this for now. Before when we are using "block" component instead of "view" component, the underlining bar exists under icons. But in "view" it seems to be different in iOS. Anyway it still works currently.

**Pull request merged**
